name: clean_arch
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  connectivity_plus: ^6.1.1
  animated_introduction: ^1.0.4
  awesome_dialog: ^2.1.1
  dot_curved_bottom_nav: ^0.0.1
  animate_do: ^3.3.4
  flutter_staggered_animations: ^1.0.0
  flutter_swiper_view: ^1.1.6
  like_button: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
